"""Migration round trip and model/migration drift check against real PostgreSQL."""

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect
from sqlalchemy.pool import NullPool

from app.core.config import Settings, to_sync_database_url

pytestmark = pytest.mark.integration

EXPECTED_TABLES = {
    "recipes",
    "ingredients",
    "recipe_steps",
    "cooking_suggestions",
    "media_assets",
    "step_images",
    "ingredient_images",
    "blogs",
    "jobs",
}
EXPECTED_ENUMS = {
    "language",
    "recipe_status",
    "job_status",
    "job_step",
    "media_type",
    "blog_status",
    "step_image_status",
}


def _tables_and_enums(database_url: str) -> tuple[set[str], set[str]]:
    engine = create_engine(to_sync_database_url(database_url), poolclass=NullPool)
    try:
        inspector = inspect(engine)
        tables = set(inspector.get_table_names()) - {"alembic_version"}
        enums = {enum["name"] for enum in inspector.get_enums()}  # type: ignore[attr-defined]
    finally:
        engine.dispose()
    return tables, enums


def test_upgrade_downgrade_upgrade_round_trip(
    alembic_config: Config, settings: Settings, migrated_database: None
) -> None:
    tables, enums = _tables_and_enums(settings.test_database_url)
    assert tables >= EXPECTED_TABLES
    assert enums >= EXPECTED_ENUMS

    command.downgrade(alembic_config, "base")
    tables, enums = _tables_and_enums(settings.test_database_url)
    assert tables == set()
    assert enums.isdisjoint(EXPECTED_ENUMS), "downgrade must drop the enum types"

    command.upgrade(alembic_config, "head")
    tables, _ = _tables_and_enums(settings.test_database_url)
    assert tables >= EXPECTED_TABLES


def test_models_and_migrations_have_no_drift(
    alembic_config: Config, migrated_database: None
) -> None:
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"Models differ from migrations: {exc}")
